go.mod
go.sum
main.go

* go.mod: update to latest thanos
* main.go: fix flags
* main.go: ensure signal chan is buffered
* main.go: ensure chans are closed
cc @metalmatze

main.go: small cleanups

---

main.go
main_test.go

This PR fixes tests after the recent changes to flags, etc.
cc @metalmatze

main.go: fix tests

---

.drone.yml

.drone.yaml: add drone config

---

examples/simple.yaml

examples: add controller to example

---

.drone.yml
main.go

fixes #10 
cc @metalmatze @brancz

 main.go: fix race closing chan

---

README.md
examples/simple.yaml

README: update readme with more info

---

.drone.yml
Dockerfile

Dockerfile,.drone.yaml: add quay.io config

---

README.md
examples/simple.yaml

examples: add labels field

---

main.go

This PR attempts to store the most recent configmap md5 checksum, and when it happens as metrics to catch any inconsistencies between current and desired state. The same strategy is used by prometheus/alertmanager#coodinator.
[Another PR](https://github.com/thanos-io/thanos/pull/1378) sent to Thanos to expose similar metrics.

Store the most recent configmap checksum and timestamp as metric

---

.drone.yml
main_test.go

.drone: add gofmt step

---

main.go

cc @brancz @metalmatze @kakkoyun

main.go: add pprof routes

---

examples/manifests/serviceMonitor.yaml
jsonnet/lib/thanos-receive-controller.libsonnet

This PR adds missing service monitor resource

Add missing service monitor

---

main_test.go

This PR fixes minor issues that has been introduced by previous PR #30.
cc @brancz

Improve clarity of tests

---

examples/alerts.yaml
jsonnet/thanos-receive-controller-mixin/alerts/alerts.libsonnet

Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>
cc @brancz @metalmatze

Add absent alert

---

examples/manifests/deployment.yaml
jsonnet/jsonnetfile.json
jsonnet/lib/thanos-receive-controller.libsonnet

The resources on the container are missing. This will add some defaults similar to our current usage.

Add resource requests and limits to receive-controller container

---

examples/manifests/configmap.yaml
examples/manifests/deployment.yaml
examples/manifests/role.yaml
examples/manifests/roleBinding.yaml
examples/manifests/service.yaml
examples/manifests/serviceAccount.yaml
jsonnet/lib/thanos-receive-controller.libsonnet

As discussed offline.
@bwplotka @squat @metalmatze @kakkoyun @krasi-georgiev

jsonnet/lib: Adhere to kube app label definitions

---

examples/dashboards/receive-controller.json

It seems `master` is currently broken. :man_shrugging:

Fix generated dashboard

---

examples/dashboards/receive-controller.json
jsonnet/jsonnetfile.json

This is hopefully fixing master once and for all.

Use thanos-mixin from upstream Thanos

---

jsonnet/jsonnetfile.json
main.go
main_test.go

This commit fixes all outstanding golangci-lint errors that have been
causing CI to fail for the last several weeks.
cc @kakkoyun @metalmatze

main.go,main_test.go: fix golangci-lint errors

---

examples/manifests/deployment.yaml
jsonnet/jsonnetfile.json
jsonnet/lib/thanos-receive-controller.libsonnet

Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

manifests: Remove ksonnet

---

jsonnet/lib/thanos-receive-controller.libsonnet
jsonnet/main.jsonnet

Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

jsonnet: Use functional pattern for manifests

---

main.go

https://github.com/observatorium/operator/issues/10

Set OwnerReferences for generated cm

---

main.go

Reverts observatorium/thanos-receive-controller#59
@clyang82

Revert "Set OwnerReferences for generated cm"

---

examples/manifests/deployment.yaml
jsonnet/jsonnetfile.json
jsonnet/lib/thanos-receive-controller.libsonnet

same as https://github.com/thanos-io/kube-thanos/pull/200 and https://github.com/thanos-io/kube-thanos/pull/202
@kakkoyun

jsonnet: Run as non-root

---

examples/manifests/deployment.yaml
jsonnet/lib/thanos-receive-controller.libsonnet

jsonnet: Fix fsGroup position

---

examples/manifests/deployment.yaml
jsonnet/lib/thanos-receive-controller.libsonnet

https://github.com/observatorium/operator/issues/51
Signed-off-by: clyang82 <chuyang@redhat.com>

Make securityContext configurable

---

examples/alerts.yaml
examples/dashboards/receive-controller.json
jsonnet/jsonnetfile.json
jsonnet/thanos-receive-controller-mixin/alerts/alerts.libsonnet
jsonnet/thanos-receive-controller-mixin/config.libsonnet
jsonnet/thanos-receive-controller-mixin/dashboards/dashboards.libsonnet
jsonnet/thanos-receive-controller-mixin/dashboards/defaults.libsonnet
jsonnet/thanos-receive-controller-mixin/mixin.libsonnet
tests.yaml

Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

mixin: Reflect recent changes in upstream Thanos mixin

---

jsonnet/jsonnetfile.json

Fix jsonent dependencies for thanos by pointing to main branch

---

jsonnet/lib/thanos-receive-controller.libsonnet

Signed-off-by: Ben Ye <ben.ye@bytedance.com>

Support cluster domain config in jsonnet

---

jsonnet/lib/thanos-receive-controller.libsonnet

Exposes feature #91 via jsonnet

jsonnet: Add config for allow-only-read-replicas flag

---

examples/dashboards/receive-controller.json

This addresses the comment in:
https://github.com/observatorium/thanos-receive-controller/pull/120#issuecomment-1723980478.

examples: regenerate to fix CI
