observatorium/thanos-receive-controller

main.go
main_test.go

This commit corrects the generated stable DNS names for the hashring
endpoints following the details in:
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id.
fixes: #3 
cc @metalmatze @brancz

main.go: use correct format for pod dns

---

.drone.yml

Use proxy.golang.org. I have seen that it takes 90s to get all dependencies. This reduces our time to 10s.
/cc @brancz @squat

Use GOPROXY with proxy.golang.org

---

.drone.yml

Right now the binary is dynamically linked due to CGO_ENABLED=1. This
causes the following error when executing inside the alpine container:
```
/usr/bin/thanos-receive-controller: not found
```
This fixes that error by splitting the test phase into an explicit
testing and building phase.
cc @metalmatze

.drone: make binary statically linked

---

.drone.yml
.gitignore

This commit ensures that any time a commit is pushed to master, the
resulting container image will be tagged both with latest as well as a
tag containing the branch, date, and hash as is the case in Thanos e.g.
master-2019-07-16-d924771
cc @metalmatze @kakkoyun

.drone.yml: ensure container is tagged with hash

---

main.go

This PR adds new metrics to monitor hash-rings.
It exposes the number of nodes and tenants per hash-ring.
\cc @squat @metalmatze

Add Hash-ring metrics

---

README.md
examples/simple.yaml
main.go
main_test.go

This commit modifies the controller to match statefulsets to hashrings
using a label rather than the statefulset name. This is important
because resource names are tied to infrastructure logic, not business
logic. Furthermore, most thanos-receive statefulsets names will always
have a `thanos-receive-` prefix, meaning that every hashring name would
also have to have that prefix. This change allows us to decouple
infrastructure and business.
cc @metalmatze @kakkoyun

main.go: find hashring name in label, not sts name

---

main.go
main_test.go

We need to use the statefulset name, not the hashring name in the DNS
name.
cc @metalmatze @aditya-konarde

main: use statefulset name in endpoints

---

.golangci.yml
Makefile
examples/alerts.yaml
go.mod
go.sum
jsonnet/thanos-receive-controller-mixin/alerts/alerts.libsonnet
main.go
main_test.go
tests.yaml

This PR,
* removes redundant alert for stale config changes
* ensures metrics correctly incremented when configmap first created
* ensures configmap does not get updated if hashring has not changed
* introduces a couple of test helper functions

Configmap updates

---

main.go

This commit ensures that the hash metric is always set, this way if the
controller is re-started after the configmap is already correctly
deployed, the metric will be set and no alert will fire.
cc @kakkoyun @aditya-konarde

main.go: always set hash metric

---

main.go

pprof.Index automatically delegates to the profile handlers accessible
via `pprof.Handler(...)`, but not ALL profiles. This commit adds support
for the missing profiles.
reference: https://golang.org/src/net/http/pprof/pprof.go?s=8862:9042#L260
cc @kakkoyun @metalmatze

main.go: add missing pprof handlers

---

main.go
main_test.go

This commit updates the controller to generate gRPC endpoints rather
than HTTP endpoints, following
https://github.com/thanos-io/thanos/pull/1970.
cc @kakkoyun @metalmatze

main.go: controller generate gRPC endpoints

---

examples/dashboards/receive-controller.json
jsonnet/thanos-receive-controller-mixin/dashboards/dashboards.libsonnet

The rate should show a constant rate of reconciles and changes. Next to those 2 graphs we still have an extra error graph.

Show the rate of reconciles and configmap changes

---

examples/dashboards/receive-controller.json
jsonnet/jsonnetfile.json
jsonnet/thanos-receive-controller-mixin/dashboards/defaults.libsonnet

Various tools in the SRE space use UTC as the default to make it
effortless during incidents to not have to calculate between timezones.
Just an example, both Prometheus and Thanos default to this behavior as
well. People can still override this in downstream usage, but I think we
should be promoting best practices.
@observatorium/maintainers

mixin: Default dashboards to UTC

---

Dockerfile

Move to gcr.io/distroless/static image which has non-root user.
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
Fixes #56

Move to non-root container

---

go.mod
go.sum

Fix this issue in downstream build:
```
The command "go mod download" failed with: go: k8s.io/client-go@v12.0.0+incompatible: reading http://cachito-athens/k8s.io/client-go/@v/v12.0.0+incompatible.mod: 404 Not Found
```

fix downstream build issue

---

go.mod
go.sum
main.go
main_test.go

Hi, in my case endpoints cannot contain clusterName. Without this change there is extra dot after svc. Would you be willing to accept this change?
Thank you.

when clustername is empty remove extra dot in endpoints

---

go.mod
go.sum
main.go

This is crucial to not send requests to receivers too early.
In combination with https://github.com/thanos-io/thanos/pull/3845 for quicker reloading of Thanos Receive Routes I was able to achieve > 99% availability in errors+latency while scaling up from 3 replicas to 20.

Probe Statefulset Pods until healthy upon scale up

---

Dockerfile

Golang versions 1.13 and 1.14 are no longer supported. For security compliance, we need to upgrade golang to 1.16.
Signed-off-by: Song Song Li <ssli@redhat.com>

upgrade golang to 1.16

---

examples/manifests/deployment.yaml
jsonnet/lib/thanos-receive-controller.libsonnet

ref: https://github.com/observatorium/operator/issues/76
Signed-off-by: morvencao <lcao@redhat.com>

Make imagePullPolicy configurable.

---

README.md
go.mod
go.sum
main.go

Based on work done in #89
This change adds a flag `--allow-only-ready-replicas` that changes the behavior of controller on a scale up - if enabled, the controller will first wait on all replicas to be ready before adding them to the hashring. The feature is documented as well.

Add feature to wait on ready replicas on scaling up 

---

examples/manifests/role.yaml
jsonnet/lib/thanos-receive-controller.libsonnet

The `allow-only-ready-replicas` feature requires permission to get pods. Otherwise the following error occurs:
> failed polling until pod is ready" pod=thanos-receive-3 duration=4.340636ms err="pods " thanos-receive-3" is forbidden: User "system:serviceaccount:thanos:thanos-receive-controller" cannot get resource "pods" in API group "" in the namespace "thanos"
This PR adds the necessary permission to the example manifest, as well as the Jsonnet code.

Add permission to get pods to RBAC Role

---

README.md
jsonnet/lib/thanos-receive-controller.libsonnet
main.go

This change allows the user, behind a flag, to provide an actual real world view of the replicas that exist in an operable state within the hashring.
A [previous comment](https://github.com/observatorium/thanos-receive-controller/pull/91#issuecomment-1240656578) warned about the consequences of adjusting the hashring during scale down events. However, this view only makes sense and works under the assumption that the disruption is temporary or unintended. We believe there are some benefits to supports this behaviour:
- Manually scaling down a StatefulSet and removing _n_ replicas
- Configuring a StatefulSet scaling with HPA
- Reducing error rate during update events
Configuring this flag allows the operator to provide a realistic view of the hashring and from testing, we have seen that …

Support updating the hashring during scaledown/disruptions

---

jsonnet/thanos-receive-controller-mixin/config.libsonnet
jsonnet/thanos-receive-controller-mixin/dashboards/defaults.libsonnet

This commit allow specifying the instance name filter, in order to filter the datasources shown on the dashboards.
This is similar to the change made in Thanos mixin here: https://github.com/thanos-io/thanos/pull/6273

Mixin: Allow specifying an instance name filter

---

jsonnet/thanos-receive-controller-mixin/alerts/alerts.libsonnet
jsonnet/thanos-receive-controller-mixin/config.libsonnet
jsonnet/thanos-receive-controller-mixin/dashboards/dashboards.libsonnet

Fix typo in the mixin.
Note: this is a breaking change for anyone changing this value downstream.

Mixin: Correctly spell `hierarchies`

---

examples/manifests/deployment.yaml
jsonnet/lib/thanos-receive-controller.libsonnet

**What this PR does / why we need it:**
- Changes the `serviceAccount` key which is a depreciated alias for `serviceAccountName`

manifests: Update K8s depracated serviceAccount key

---

main.go

`annotatePods()` only affects pods which are running in RouterIngestor mode: Pods which declare a hashring file AND are also a member of that hashring. It works by iterating through every expected pod in the STS. This has a couple of problems:
1. If the size of the STS is larger than the number of running pods (failed pods) there will be failures to update those pods. This is a nuisance error.
2. If we're operating in a split setup (Router separately from Ingestor) the controller does not know to annotate the Router pods, it only annotates the discovered STS pods. This means the Routers are left to reload their CM on their fallback timeout, instead of immediately.
3. Only StatefulSets are affected, if using Routers as Deployments instead of STS, the controller will not annotate them with …

annotate all pods under our domain, not just those in the STS
